steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--build-arg',
    'PROJECT_ID=$PROJECT_ID',
    '-t',
    'gcr.io/$PROJECT_ID/web',
    '.'
  ]
images:
- 'gcr.io/$PROJECT_ID/web'
