import CloseIcon from '@material-ui/icons/Close';
import RoomIcon from '@material-ui/icons/Room';
import ShoppingCartIcon from '@material-ui/icons/ShoppingCart';
import LocalHospitalIcon from '@material-ui/icons/LocalHospital';
import LocalPharmacyIcon from '@material-ui/icons/LocalPharmacy';
import LocalGasStationIcon from '@material-ui/icons/LocalGasStation';
import AccountBalanceIcon from '@material-ui/icons/AccountBalance';
import { mapValues } from 'lodash';

const placeTypes = {
  accounting: { open: null },
  airport: { open: true },
  amusement_park: { open: false },
  aquarium: { open: false },
  art_gallery: { open: false },
  atm: { open: true, Icon: AccountBalanceIcon },
  bakery: { open: true, Icon: ShoppingCartIcon },
  bank: { open: true, Icon: AccountBalanceIcon },
  bar: { open: false },
  beauty_salon: { open: false },
  bicycle_store: { open: null },
  book_store: { open: false },
  bowling_alley: { open: false },
  bus_station: { open: true },
  cafe: { open: false },
  campground: { open: false },
  car_dealer: { open: false },
  car_rental: { open: null },
  car_repair: { open: null },
  car_wash: { open: null },
  casino: { open: false },
  cemetery: { open: true },
  church: { open: null },
  city_hall: { open: true },
  clothing_store: { open: false },
  convenience_store: { open: true, Icon: ShoppingCartIcon },
  courthouse: { open: true },
  dentist: { open: true, Icon: LocalHospitalIcon },
  department_store: { open: false },
  doctor: { open: true, Icon: LocalHospitalIcon },
  drugstore: { open: true, Icon: LocalPharmacyIcon },
  electrician: { open: null },
  electronics_store: { open: false },
  embassy: { open: true },
  fire_station: { open: true },
  florist: { open: false },
  funeral_home: { open: true },
  furniture_store: { open: false },
  gas_station: { open: true, Icon: LocalGasStationIcon },
  grocery_or_supermarket: { open: true, Icon: ShoppingCartIcon },
  gym: { open: false },
  hair_care: { open: false },
  hardware_store: { open: true }, // FIXME
  hindu_temple: { open: false },
  home_goods_store: { open: true, Icon: ShoppingCartIcon },
  hospital: { open: true, Icon: LocalHospitalIcon },
  insurance_agency: { open: null },
  jewelry_store: { open: false },
  laundry: { open: null },
  lawyer: { open: true },
  library: { open: false },
  light_rail_station: { open: true },
  liquor_store: { open: true },
  local_government_office: { open: true },
  locksmith: { open: false },
  lodging: { open: false },
  meal_delivery: { open: true },
  meal_takeaway: { open: true },
  mosque: { open: false },
  movie_rental: { open: false },
  movie_theater: { open: false },
  moving_company: { open: true },
  museum: { open: false },
  night_club: { open: false },
  painter: { open: true },
  park: { open: true },
  parking: { open: true },
  pet_store: { open: false },
  pharmacy: { open: true, Icon: LocalPharmacyIcon },
  physiotherapist: { open: true },
  plumber: { open: true },
  police: { open: true },
  post_office: { open: true },
  primary_school: { open: false },
  real_estate_agency: { open: true },
  restaurant: { open: false },
  roofing_contractor: { open: true },
  rv_park: { open: true },
  school: { open: false },
  secondary_school: { open: false },
  shoe_store: { open: false },
  shopping_mall: { open: false },
  spa: { open: false },
  stadium: { open: false },
  storage: { open: true },
  store: { open: true },
  subway_station: { open: true },
  supermarket: { open: true, Icon: ShoppingCartIcon },
  synagogue: { open: false },
  taxi_stand: { open: true },
  tourist_attraction: { open: true },
  train_station: { open: true },
  transit_station: { open: true },
  travel_agency: { open: false },
  university: { open: false },
  veterinary_care: { open: true },
  zoo: { open: false },
  administrative_area_level_1: { open: false },
  administrative_area_level_2: { open: false },
  administrative_area_level_3: { open: false },
  administrative_area_level_4: { open: false },
  administrative_area_level_5: { open: false },
  archipelago: { open: false },
  colloquial_area: { open: false },
  continent: { open: false },
  country: { open: false },
  establishment: { open: false },
  finance: { open: false },
  floor: { open: false },
  food: { open: false },
  general_contractor: { open: false },
  geocode: { open: false },
  health: { open: false, Icon: LocalHospitalIcon },
  intersection: { open: false },
  locality: { open: false },
  natural_feature: { open: false },
  neighborhood: { open: false },
  place_of_worship: { open: false },
  point_of_interest: { open: false },
  political: { open: false },
  post_box: { open: false },
  postal_code: { open: false },
  postal_code_prefix: { open: false },
  postal_code_suffix: { open: false },
  postal_town: { open: false },
  premise: { open: false },
  room: { open: false },
  route: { open: false },
  street_address: { open: false },
  street_number: { open: false },
  sublocality: { open: false },
  sublocality_level_1: { open: false },
  sublocality_level_2: { open: false },
  sublocality_level_3: { open: false },
  sublocality_level_4: { open: false },
  sublocality_level_5: { open: false },
  subpremise: { open: false },
  town_square: { open: false },
};

export default mapValues(placeTypes, (placeType) => ({
  Icon: placeType.open ? RoomIcon : CloseIcon,
  ...placeType,
}));
