import AccountBalanceIcon from '@material-ui/icons/AccountBalance';
import CloseIcon from '@material-ui/icons/Close';
import LocalGasStationIcon from '@material-ui/icons/LocalGasStation';
import LocalHospitalIcon from '@material-ui/icons/LocalHospital';
import LocalPharmacyIcon from '@material-ui/icons/LocalPharmacy';
import NotListedLocationIcon from '@material-ui/icons/NotListedLocation';
import RoomIcon from '@material-ui/icons/Room';
import ShoppingCartIcon from '@material-ui/icons/ShoppingCart';
import { mapValues } from 'lodash';

const placeTypes = {
  accounting: { open: null },
  airport: { open: true },
  amusement_park: { open: false },
  aquarium: { open: false },
  art_gallery: { open: false },
  atm: { open: true, Icon: AccountBalanceIcon },
  bakery: { open: true, Icon: ShoppingCartIcon },
  bank: { open: true, Icon: AccountBalanceIcon },
  bar: { open: false },
  beauty_salon: { open: false },
  bicycle_store: { open: null },
  book_store: { open: false },
  bowling_alley: { open: false },
  bus_station: { open: true },
  cafe: { open: false },
  campground: { open: false },
  car_dealer: { open: false },
  car_rental: { open: null },
  car_repair: { open: null },
  car_wash: { open: null },
  casino: { open: false },
  cemetery: { open: true },
  church: { open: null },
  city_hall: { open: true },
  clothing_store: { open: false },
  convenience_store: { open: true, Icon: ShoppingCartIcon },
  courthouse: { open: true },
  dentist: { open: true, Icon: LocalHospitalIcon },
  department_store: { open: false },
  doctor: { open: true, Icon: LocalHospitalIcon },
  drugstore: { open: true, Icon: LocalPharmacyIcon },
  electrician: { open: null },
  electronics_store: { open: false },
  embassy: { open: true },
  fire_station: { open: true },
  florist: { open: false },
  funeral_home: { open: true },
  furniture_store: { open: false },
  gas_station: { open: true, Icon: LocalGasStationIcon },
  grocery_or_supermarket: { open: true, Icon: ShoppingCartIcon },
  gym: { open: false },
  hair_care: {
    open: false,
    text:
      'Dienstleistungsbetriebe im Bereich der Körperpflege sind wegen erhöhter Ansteckungsgefahr derzeit geschlossen.',
  },
  hardware_store: { open: true }, // FIXME
  hindu_temple: { open: false },
  home_goods_store: { open: true, Icon: ShoppingCartIcon },
  hospital: { open: true, Icon: LocalHospitalIcon },
  insurance_agency: { open: null },
  jewelry_store: { open: false },
  laundry: { open: null },
  lawyer: { open: true },
  library: { open: false },
  light_rail_station: { open: true },
  liquor_store: { open: true },
  local_government_office: { open: true },
  locksmith: { open: false },
  lodging: { open: false },
  meal_delivery: { open: true },
  meal_takeaway: { open: true },
  mosque: { open: false },
  movie_rental: { open: false },
  movie_theater: { open: false },
  moving_company: { open: true },
  museum: { open: false },
  night_club: { open: false },
  painter: { open: true },
  park: { open: true },
  parking: { open: true },
  pet_store: { open: false },
  pharmacy: { open: true, Icon: LocalPharmacyIcon },
  physiotherapist: { open: true },
  plumber: { open: true },
  police: { open: true },
  post_office: { open: true },
  primary_school: { open: false },
  real_estate_agency: { open: true },
  restaurant: { open: false },
  roofing_contractor: { open: true },
  rv_park: { open: true },
  school: { open: false },
  secondary_school: { open: false },
  shoe_store: { open: false },
  shopping_mall: { open: false },
  spa: { open: false },
  stadium: { open: false },
  storage: { open: true },
  store: { open: true },
  subway_station: { open: true },
  supermarket: { open: true, Icon: ShoppingCartIcon },
  synagogue: { open: false },
  taxi_stand: { open: true },
  tourist_attraction: { open: true },
  train_station: { open: true },
  transit_station: { open: true },
  travel_agency: { open: false },
  university: { open: false },
  veterinary_care: { open: true },
  zoo: { open: false },
  administrative_area_level_1: { open: null },
  administrative_area_level_2: { open: null },
  administrative_area_level_3: { open: null },
  administrative_area_level_4: { open: null },
  administrative_area_level_5: { open: null },
  archipelago: { open: null },
  colloquial_area: { open: null },
  continent: { open: null },
  country: { open: null },
  establishment: { open: null },
  finance: { open: null },
  floor: { open: null },
  food: { open: null },
  general_contractor: { open: null },
  geocode: { open: null },
  health: { open: true, Icon: LocalHospitalIcon },
  intersection: { open: null },
  locality: { open: null },
  natural_feature: { open: null },
  neighborhood: { open: null },
  place_of_worship: { open: null },
  point_of_interest: { open: null },
  political: { open: null },
  post_box: { open: null },
  postal_code: { open: null },
  postal_code_prefix: { open: null },
  postal_code_suffix: { open: null },
  postal_town: { open: null },
  premise: { open: null },
  room: { open: null },
  route: { open: null },
  street_address: { open: null },
  street_number: { open: null },
  sublocality: { open: null },
  sublocality_level_1: { open: null },
  sublocality_level_2: { open: null },
  sublocality_level_3: { open: null },
  sublocality_level_4: { open: null },
  sublocality_level_5: { open: null },
  subpremise: { open: null },
  town_square: { open: null },
};

function fallbackIcon(isOpen) {
  if (isOpen === true) {
    return RoomIcon;
  }
  if (isOpen === false) {
    return CloseIcon;
  }
  return NotListedLocationIcon;
}

export default mapValues(placeTypes, (placeType) => ({
  Icon: fallbackIcon(placeType.open),
  ...placeType,
}));
